name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  db-schema-validate:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: robotics
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Wait for Postgres
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U postgres && break
            sleep 3
          done
      - name: Apply schema modules in order
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: robotics
        run: |
          psql -v ON_ERROR_STOP=1 -f database/01_extensions.sql
          psql -v ON_ERROR_STOP=1 -f database/10_core.sql
          psql -v ON_ERROR_STOP=1 -f database/20_sales.sql
          psql -v ON_ERROR_STOP=1 -f database/30_manufacturing_structure.sql
          psql -v ON_ERROR_STOP=1 -f database/31_manufacturing_execution.sql
          psql -v ON_ERROR_STOP=1 -f database/32_manufacturing_maintenance.sql
          psql -v ON_ERROR_STOP=1 -f database/33_manufacturing_telemetry.sql
          psql -v ON_ERROR_STOP=1 -f database/40_views.sql
          psql -v ON_ERROR_STOP=1 -f database/50_triggers.sql
          psql -v ON_ERROR_STOP=1 -f database/60_indexes.sql
      - name: Smoke test
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: robotics
        run: |
          psql -v ON_ERROR_STOP=1 -c "SELECT COUNT(*) FROM departments;"